version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/galaxy-root
permissions:
  - object: /home/ubuntu/
    owner: ubuntu
    group: ubuntu
    type:
      - directory
hooks:
  BeforeInstall:
    - location: ./shutdown.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: ./start.sh
      timeout: 300
      runas: ubuntu



