version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo `pwd`
      - echo build started at `date`
      # - mvn clean install
      - mvn clean package
