version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - openssl enc -d -aes-256-ecb -md md5 -in ./galaxy-gateway/src/main/resources/bootstrap.yml.secrets -out ./galaxy-gateway/src/main/resources/bootstrap.yml -k $SECRETS_KEY
      - mvn clean install

artifacts:
  files:
    - 'galaxy-gateway/target/galaxy-gateway-1.0.0.jar'
    - 'galaxy-gateway/appspec.yml'
    - 'galaxy-gateway/deploy/check.sh'
    - 'galaxy-gateway/deploy/install.sh'
    - 'galaxy-gateway/deploy/start.sh'
    - 'galaxy-gateway/deploy/stop.sh'
  discard-paths: yes

