version: 0.0
os: linux
files:
  - source: target
    destination: /home/ec2-user/jar
hooks:
  ApplicationStop:
    - location: deploy/stop.sh
      timeout: 300
      runas: root
  BeforeInstall:
    - location: deploy/check.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/start.sh
      timeout: 300
      runas: root

