version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - cd ./galaxy-eureka
      - echo build started at `date`
      - mvn clean install

artifacts:
  files:
    - 'target/galaxy-eureka-1.0.0.jar'
    - 'appspec.yml'
    - 'deploy/check.sh'
    - 'deploy/install.sh'
    - 'deploy/start.sh'
    - 'deploy/stop.sh'
  discard-paths: yes

