version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - cd ./galaxy-eureka
      - echo build started at `date`
      - mvn clean install
      # - mvn clean package

artifacts:
  files:
    - target/*.jar
    - ./appspec.yml
    - deploy/*
  discard-paths: yes
