version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo current path is `pwd`
      - echo current folders is `ls`
      - echo build started at `date`
      # - mvn clean install
      - mvn clean package

artifacts:
  files:
    - target
    - appspec.yml
    - deploy
  discard-paths: yes