version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - cd ../galaxy-common
      - mvn clean install
      - cd galaxy-eureka
      - mvn clean install -Dmaven.test.skip=true

artifacts:
  files:
    - target
    - appspec.yml
    - deploy
  discard-paths: yes
