version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8

  build:
    commands:
      - echo build started at `date`

  post_build:
    commands:
      - mvn clenan package -B
artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes
