version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - cd ./galaxy-eureka
      - echo build started at `date`
      - openssl enc -d -aes-256-ecb -md md5 -in ./src/main/resources/bootstrap.yml.secrets -out ./src/main/resources/bootstrap.yml -k $SECRETS_KEY
      - mvn clean install

artifacts:
  files:
    - 'galaxy-eureka/target/galaxy-eureka-1.0.0.jar'
    - 'galaxy-eureka/appspec.yml'
    - 'galaxy-eureka/deploy/check.sh'
    - 'galaxy-eureka/deploy/install.sh'
    - 'galaxy-eureka/deploy/start.sh'
    - 'galaxy-eureka/deploy/stop.sh'
  discard-paths: yes



