version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - mvn clean package -B

artifacts:
  files:
    - target/*.jar
    - appspec.yml
  discard-paths: yes
