version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - mvn clean install

artifacts:
  files:
    - target
    - appspec.yml
    - deploy
  discard-paths: yes