version: 0.2

phases:
  pre_build:
    commands:
      - export REPOSITORY_URI=688559712485.dkr.ecr.us-west-1.amazonaws.com/galaxy-eureka
      - export COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - export IMAGE_TAG=${COMMIT_HASH:=latest}
      - export PROJECT=galaxy-eureka
  build:
    commands:
      - echo build started at `date`
      - mvn clean package -B
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo build completed at `date`
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
artifacts:
  files:
    - target/galaxy-eureka-1.0.0.jar
    - shutdown.sh
    - start.sh
    - appspec.yml
  discard-paths: yes