version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo current path is `pwd`
      - echo current folders are `ls -al`
      - cd ./galaxy-eureka
      - - echo moved to path `pwd`
      - - echo moved folders are `ls -al`
      - echo build started at `date`
      # - mvn clean install
      - mvn clean package

artifacts:
  files:
    - target
    - appspec.yml
    - deploy
  discard-paths: yes