version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - mvn clean install

artifacts:
  files:
    - 'galaxy-config/target/galaxy-config-1.0.0.jar'
    - 'galaxy-config/appspec.yml'
    - 'galaxy-config/deploy/check.sh'
    - 'galaxy-config/deploy/install.sh'
    - 'galaxy-config/deploy/start.sh'
  discard-paths: yes

