version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - openssl enc -d -aes-256-ecb -md md5 -in ./galaxy-config/src/main/resources/bootstrap.yml.secrets -out ./galaxy-config/src/main/resources/bootstrap.yml -k $SECRETS_KEY
      - mvn clean install

artifacts:
  files:
    - 'galaxy-config/target/galaxy-config-1.0.0.jar'
    - 'galaxy-config/appspec.yml'
    - 'galaxy-config/deploy/check.sh'
    - 'galaxy-config/deploy/install.sh'
    - 'galaxy-config/deploy/start.sh'
    - 'galaxy-config/deploy/stop.sh'
  discard-paths: yes

