version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo current path is `pwd`
      - echo current lst is `ls -list`
      - echo build started at `date`
      - openssl enc -d -aes-256-ecb -md md5 -in ./galaxy-upload/src/main/resources/bootstrap.yml.secrets -out ./galaxy-upload/src/main/resources/bootstrap.yml -k $SECRETS_KEY
      - mvn clean install

artifacts:
  files:
    - 'galaxy-upload/target/galaxy-upload-1.0.0.jar'
    - 'galaxy-upload/appspec.yml'
    - 'galaxy-upload/deploy/check.sh'
    - 'galaxy-upload/deploy/install.sh'
    - 'galaxy-upload/deploy/start.sh'
    - 'galaxy-upload/deploy/stop.sh'
  discard-paths: yes

