version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8

  build:
    commands:
      - echo build started at `date`
      - mvn clean install

artifacts:
  files:
    - 'galaxy-upload/target/galaxy-upload-1.0.0.jar'
    - 'galaxy-upload/appspec.yml'
    - 'galaxy-upload/deploy/check.sh'
    - 'galaxy-upload/deploy/install.sh'
    - 'galaxy-upload/deploy/start.sh'
    - 'galaxy-upload/deploy/stop.sh'
  discard-paths: yes

